Project/Order/Models/Food.cs
namespace Order.Models
{
    public class Food
    {
        public int FoodId{ get; set; }
        public string? FoodName { get; set; }
        public int SaleNum{ get; set; }
        public string SaleRank { get; set; }
        public string FoodPrice { get; set; }
        public string FoodIntro { get; set; }
        public string? FoodPic { get; set; }
        public int ShopId{ get; set; }
    
    }
}

Project/Order/Controllers/FoodDetailController.cs
using Microsoft.AspNetCore.Mvc;
using Order.Models;
using Microsoft.AspNetCore.Authorization;

namespace Order.Controllers
{
    [Authorize]
    public class FoodDetailController : Controller
    {
        private IFoodRepository _foodRepository;
        public FoodDetailController(IFoodRepository foodRepository)
        {
            _foodRepository = foodRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult FoodDetail(int id)
        {
            return View(_foodRepository.GetFoodById(id));
        }
    }
}

Project/Order/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Order.Models;
using System.Diagnostics;

namespace Order.Controllers
{
    public class HomeController : Controller
    {
        private IShopRepository _shopRepository;
        private IFoodRepository _foodRepository;
        public HomeController(IShopRepository shopRepository, IFoodRepository foodRepository)
        {
            _shopRepository = shopRepository;
            _foodRepository = foodRepository;
        }
        private readonly ILogger<HomeController> _logger;

       

        public IActionResult Index()
        {
            var shops = _shopRepository.GetAllShops();
            return View(shops);
        }
		
		public IActionResult ShopDetail(int id)
        {
            var shop = _shopRepository.GetShopById(id);
            var foods = _foodRepository.GetFoodByShopId(id);
            shop.Foods = foods; 
            return View(shop);
        }
		
		public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Project/Order/Views/Home/Food.cshtml
@{
    ViewData["Title"] = "Index";
}


<section class="single-product">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<ol class="breadcrumb">
					<li><a href="index.html">首页</a></li>
					<li><a href="shop.html">南京</a></li>
					<li class="active">盐水鸭</li>
				</ol>
			</div>
		</div>
		<div class="row mt-20">
			<div class="col-md-5">
				<div class="single-product-slider">
					<div id='carousel-custom' class='carousel slide' data-ride='carousel'>
						<div class='carousel-outer'>
							<!-- me art lab slider -->
							<div class='carousel-inner '>
								<div class='item active'>
									<img src="~/images/shop/single-products/food1.jpg" alt='' data-zoom-image="~/images/shop/single-products/food1.jpg" />
								</div>

							</div>

							<!-- sag sol -->
							<a class='left carousel-control' href='#carousel-custom' data-slide='prev'>
								<i class="tf-ion-ios-arrow-left"></i>
							</a>
							<a class='right carousel-control' href='#carousel-custom' data-slide='next'>
								<i class="tf-ion-ios-arrow-right"></i>
							</a>
						</div>

						<!-- thumb -->
						
					</div>
				</div>
			</div>
			<div class="col-md-7">
				<div class="single-product-details">
					<h2>盐水鸭</h2>
					<p class="product-price">价格：￥ 300</p>
					<p>销量：200</p>
					<p>配料：XXX；XXX；XXX；XXX</p>
					<p>权益：七天无理由</p>
					<p class="product-description mt-20">
						
						盐水鸭的蛋白质含量为16%~25%，脂肪6%~7.5%，属于高蛋白、低脂肪的食品，氨基酸全面，此外还含有钙、磷、铁、硫胺素、核黄酸、尼克酸和VA、VD、VE等…
						盐水鸭很适合身体虚弱疲乏者，因为鸭肉正可以起到补血的功效，食疗效果明显，特别是皮肤干燥者，可以经常喝些鸭汤。
					</p>
					
					<a href="cart.html" class="btn btn-main mt-20">加入购物车</a>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<div class="tabCommon mt-20">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#details" aria-expanded="true">详情</a></li>
						
					</ul>
					<div class="tab-content patternbg">
						<div id="details" class="tab-pane fade active in">
							<h4>商品描述</h4>
							<p>
								盐水鸭的蛋白质含量为16%~25%，脂肪6%~7.5%，属于高蛋白、低脂肪的食品，氨基酸全面，此外还含有钙、磷、铁、硫胺素、核黄酸、尼克酸和VA、VD、VE等…
								盐水鸭很适合身体虚弱疲乏者，因为鸭肉正可以起到补血的功效，食疗效果明显，特别是皮肤干燥者，可以经常喝些鸭汤。
							</p>
							<p></p>
						</div>
						
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

Project/Order/Views/Home/Index.cshtml
@model IEnumerable<Order.Models.Shop>;//通过model引入店铺的数据模型shop

@{
    ViewData["Title"] = "首页";
}

<!--轮播图-->
<div class="hero-slider">
	<div class="slider-item th-fullpage hero-area" style="background-image: url(images/slider/slider1.png);">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 text-right">
					<p data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".1">南京馆</p>
					<h1 data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".5">盐水鸭</h1>
					<a data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".8" class="btn" href="https://localhost:44396/fooddetail/fooddetail/1">立即购买</a>
				</div>
			</div>
		</div>
	</div>
	<div class="slider-item th-fullpage hero-area" style="background-image: url(images/slider/slider2.png);">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 text-left">
					<p data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".1">泰州馆</p>
					<h1 data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".5">黄桥烧饼</h1>
					<a data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".8" class="btn" href="https://localhost:44396/fooddetail/fooddetail/10">立即购买</a>
				</div>
			</div>
		</div>
	</div>
	<div class="slider-item th-fullpage hero-area" style="background-image: url(images/slider/slider3.png);">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 text-left">
					<p data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".1">上饶馆</p>
					<h1 data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".5">铅山米粉</h1>
					<a data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".8" class="btn" href="https://localhost:44396/fooddetail/fooddetail/26">立即购买</a>
				</div>
			</div>
		</div>
	</div>
</div>
<!--商店入口-->
<section class="product-category section">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="title text-center">
					<h2>我们的家乡馆</h2>
					<div class="line-dec"></div>
				</div>
			</div>
			
			@foreach (var shop in Model)
			{
				<div class="col-md-6">
					<div class="category-box">
					<a asp-controller="Home" asp-action="ShopDetail" asp-route-id="@shop.ShopId">
						<div style="background-color:rgba(0,0,0)">
								<img src="@shop.ShopImgurl" alt="" style="width:670px;height:440px;opacity:0.8" />
						</div>
						<div class="content" >
							<h3 style="color:#e8e8e8">
								@shop.ShopName
							</h3>
								<p style="color:#e8e8e8">@shop.Address</p>
							<br>
							<div style="width:400px">
									<p style="color:#e8e8e8">@shop.ShopDescription</p>
							</div>
							
							
						</div>
					</a>
				</div>
				</div>
			}

		</div>
	</div>
</section>

Project/Order/Views/Home/ShopDetail.cshtml
@model Order.Models.Shop;

@{
    ViewData["Title"] = "店铺";
}


<section class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="content col-md-11">
                    <h1 class="page-name">@Model.ShopName</h1>
                    <p>@Model.ShopIntro</p>
                    
                </div>
            </div>
        </div>
    </div>
</section>


<section class="products section">
	<div class="container">
		<div class="row">
			<!-- 1-->
			@foreach (var food in Model.Foods)
			{
				<div class="col-md-3">
					<div class="product-item">
						<div class="product-thumb">
							<span class="bage">Hot</span>
							<img class="img-responsive" src="@food.FoodPic" alt="product-img" style="height:280px; width:330px"/>
							<div class="preview-meta">
								<ul>
									<li>
										<a href="#!"><i class="tf-ion-ios-heart"></i></a>
									</li>
									<li>
										<a asp-controller="FoodDetail"
										   asp-action="FoodDetail"
										   asp-route-id="@food.FoodId"><i class="tf-ion-android-cart"></i></a>
									</li>
								</ul>
							</div>
						</div>
						<div class="product-content">
							<div class="card-body p-4">
								<div class="text-center">
									<!-- Product name-->
									<h4 class="fw-bolder">
											@food.FoodName
									</h4>
									<p>@food.SaleRank</p>
									<!-- Product price-->
									<span class="text-muted text-decoration-line-through">￥ @food.FoodPrice</span>
								</div>
							</div>
							<!-- Product actions-->
							<div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
								<a class="btn-1" 
								asp-controller="FoodDetail"
								   asp-action="FoodDetail"
								   asp-route-id="@food.FoodId">立即购买</a>
								
							</div>
						</div>
					</div>
				</div>
			}
			

		</div>
	</div>
</section>